social_project/socialsite/posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView


app_name='posts'

urlpatterns=[
    path('', post_comment_create_and_list_view, name='main-posts-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update', PostUpdateView.as_view(), name='post-update'),
]

social_project/socialsite/profiles/urls.py
from django.urls import path
from .views import (
                    profile_view, 
                    invites_received_view,
                    invite_profiles_list_view,
                    ProfileListView,
                    # profiles_list_view,
                    send_invitation,
                    remove_from_friends,
                    accept_invitation,
                    reject_invitation,
                    ProfileDetailView,
                    )

app_name='profiles'

urlpatterns=[
    path('myprofile', profile_view, name='profile'),
    
    path('all-profiles/', ProfileListView.as_view(), name='all-profiles-view'),
    path('<int:pk>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invitation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('my-invites/accept/', accept_invitation, name='accept-invite'),
    path('my-invites/reject/', reject_invitation, name='reject-invite'),
]

social_project/socialsite/socialsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('allauth.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

social_project/socialsite/profiles/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from .utils import get_random_code
from django.utils.text import slugify
from django.db.models import Q
from django.http import JsonResponse
# Create your models here.

class ProfileManager(models.Manager):

    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))
        print(qs)
        print("#########")

        accepted = set([])
        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.receiver)
                accepted.add(rel.sender)
        print(accepted)
        print("#########")

        available = [profile for profile in profiles if profile not in accepted]
        print(available)
        print("#########")
        return available
        

    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles




class Profile(models.Model):
    first_name = models.CharField(max_length = 200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default='no bio...', max_length=300)
    email = models.EmailField(max_length=200, blank=True)
    country = models.CharField(max_length = 200, blank=True)
    avatar = models.ImageField(default='avatar.png', upload_to='avatars/')
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    slug = models.SlugField(unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProfileManager()

    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"

    # def get_absolut_url(self):
    #     return reverse('profiles:profile-detail-view', kwargs={'pk': self.pk})

    def get_friends(self):
        return self.friends.all()
    

    def get_friends_count(self):
        return self.friends.all().count()
    
    def get_posts_no(self):
        return self.posts.all().count()

    def get_all_authors_posts(self):
        return self.posts.all()
    


    def get_all_likes_given(self):
        likes = self.like_set.all()
        total_liked = 0
        for item in likes:
            if item.value == 'Like':
                total_liked += 1

        return total_liked


    def get_all_likes_received(self):
        posts = self.posts.all()
        total_liked = 0
        
        for item in posts:
            total_liked += item.liked.all().count()
        
        return total_liked


    


    def save(self,*args, **kwargs):
        ex = False
        to_slug = self.slug
        if self.first_name and self.last_name:
            to_slug = slugify(str(self.first_name)+ ' '+ str(self.last_name))
            ex = Profile.objects.filter(slug=to_slug).exists()
            while ex:
                to_slug = slugify(to_slug + " " + str(get_random_code()))
                ex = Profile.objects.filter(slug=to_slug).exists()
        else:
            to_slug=str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)


STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)
class RelationshipManager(models.Manager):
    def invitation_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs

class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"
        

social_project/socialsite/profiles/forms.py
from django import forms
from .models import Profile

class profileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'bio', 'avatar')

social_project/socialsite/profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Profile, Relationship
from .forms import profileForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
@login_required
def profile_view(request):
    profile = Profile.objects.get(user=request.user)
    form = profileForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True
    context={
        'profile': profile,
        'form': form,
        'confirm': confirm,

    }

    return render(request, 'profiles/myprofile.html', context)

@login_required
def invites_received_view(request):
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invitation_received(receiver=profile)
    # results = list(map(lambda x: x.sender, qs))
    results = [x.sender for x in qs]
    is_empty = False

    if len(results) == 0:
        is_empty = True

    context = {
        'qs': results,
        'is_empty': is_empty,
    }

    return render(request, 'profiles/my_invites.html', context)
@login_required
def accept_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)

        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()

    return redirect('profiles:my-invites-view')

@login_required
def reject_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()

    return redirect('profiles:my-invites-view')



@login_required
def invite_profiles_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles_to_invite(user)

    context = {
        'qs': qs,
    }

    return render(request, 'profiles/to_invite_list.html', context)
    

# def profiles_list_view(request):
#     user = request.user
#     qs = Profile.objects.get_all_profiles(user)

#     context = {
#         'object_list': qs,
#         'rel_receiver': [],
#         'rel_sender': [],
#     }

#     return render(request, 'profiles/profile_list.html', context)

class ProfileDetailView(LoginRequiredMixin,DetailView):
    model = Profile
    template_name = 'profiles/detail.html'

    def get_object(self):
        pk = self.kwargs.get('pk')
        profile = Profile.objects.get(pk=pk)
        return profile
    

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []

        for item in rel_r:
            rel_receiver.append(item.receiver.user)

        for item in rel_s:
            rel_sender.append(item.sender.user)
        
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['posts'] = self.get_object().get_all_authors_posts()
        context['len_posts'] = True if len(context['posts']) > 0 else False

        return context





class ProfileListView(LoginRequiredMixin,ListView):
    model = Profile
    template_name = "profiles/profile_list.html"

    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []

        for item in rel_r:
            rel_receiver.append(item.receiver.user)

        for item in rel_s:
            rel_sender.append(item.sender.user)
        
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['is_empty'] = False

        if len(self.get_queryset()) == 0:
            context['is_empty'] = True

        return context

@login_required
def send_invitation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')

        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:profile')


@login_required
def remove_from_friends(request):
    if request.method=='POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender))
        )
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:profile')

social_project/socialsite/profiles/templates/profiles/detail.html
{% extends 'base.html' %}

{% block title %}
    Profile Detail
{% endblock title %}
{% block content %}

<!-- <div class='ui segment'> -->
    <div class="ui grid">

        <br>
        <div class="row">
            <div class="four wide column">
                <img src={{object.avatar.url}} class="ui medium rounded image" alt="profile_image">
                <h1>{{object.user}}</h1>
                <div class="ui vertical fluid menu">
                    <div class="item">
                        Posts
                        <div class="ui label">{{ object.get_posts_no }}</div>
                    </div>
                    <div class="item">
                        Likes given
                        <div class="ui label">{{ object.get_all_likes_given }}</div>
                    </div>
                    <div class="item">
                        Likes received
                        <div class="ui label">{{ object.get_all_likes_received }}</div>
                    </div>
                    <div class="item">
                        Friends
                        <div class="ui label">{{ object.get_friends_count }}</div>
                    </div>
                </div>
                    {% if object.user not in rel_receiver and object.user not in rel_sender %}
                        <form action="{% url 'profiles:send-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name='profile_pk' value="{{object.pk}}">
                            <button class="ui positive basic button mb-5 w-big" type="submit"><i class="plus square icon"></i>Add to friends</button>
                        </form>
                        {% endif %}
                        <br>
                        {% if object.user in rel_receiver and request.user not in object.friends.all %}
                            <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for Approval</button>
                                        
                        {% endif %}
    
                        {% if request.user in object.friends.all %}
                        <form action="{% url 'profiles:remove-friend' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name='profile_pk' value="{{object.pk}}">
                            
                            <button class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                        
                        </form>
                        {% endif %}
                
            </div>

            <div class="twelve wide column">
                {% if len_posts %}
                    {% for post in posts %}
                        <div class="ui segment fluid">
                            {{post.content}}
                        </div>
                    {% endfor %}

                    {% else %}
                        <h1>No posts by this user yet.</h1>
                {% endif %}
            </div>
        </div>
    </div>
<!-- </div> -->

{% endblock content %}

social_project/socialsite/profiles/templates/profiles/my_invites.html
{% extends 'base.html' %}

{% block title %}
    Invite Friends
{% endblock title %}

{% block content %}
{% if is_empty %}
    <h1>No invitation here.</h1>
{% endif %}
    <ul>
        {% for item in qs %}
            <div class="ui segment">
                <div class="ui grid">
                    <div class="row">
                        <div class="three wide column">
                            <img src={{item.avatar.url}} class="ui small circular image" alt="image">
                            
                        </div>
                        <div class="thirteen wide column">
                            <h3>{{item.user}}</h3>
                            <p>{{item.bio}}</p>
                            <a href="">
                                <button class="ui primary button w-big mb-5">See Profile</button>
                            </a>
                            <form action="{% url 'profiles:accept-invite' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name='profile_pk' value="{{item.pk}}">
                                <button type="submit" class="ui positive basic button w-big mb-5">
                                    <i class="check icon"></i>Accept Invite
                                </button>
                            </form>
                            <form action="{% url 'profiles:reject-invite' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name='profile_pk' value="{{item.pk}}">
                                <button type="submit" class="ui negative basic button w-big mb-5">
                                    <i class="close icon"></i>Reject Invite
                                </button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

    </ul>
{% endblock content %}

social_project/socialsite/profiles/templates/profiles/myprofile.html
{% extends 'base.html' %}

{% block title %}
myprofile
{% endblock title %}

{% block content %}

<!-- This is the semantic modal -->
<div class="ui modal mymodal">
    <i class="close icon"></i>
    <div class="header">
      Update your profile
    </div>
    <div class="image content">
      <div class="ui medium image">
        <img src="{{profile.avatar.url}}">
      </div>
      <div class="description">
        <div class="ui header">We've auto-chosen a profile image for you.</div>
        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="ui postive button">update</button>
      </div>
    </div>
    <div class="actions">
      <button type='submit' class="ui positive right labeled icon button">
        Update
        <i class="checkmark icon"></i>
      </button>
    </form>
    </div>
  </div>


<div class="ui segment">
    {% if confirm %}

        <div class="ui green message">Your profile has been updated</div>
        
    {% endif%}
    <h3 text='black'>My Profile: {{request.user}}</h3> 
    <div class="ui grid">

    
    <div class="row">
        <div class="six wide column">
            <img class=" ui medium rounded image " src="{{profile.avatar.url}}" alt="Profile_Pic">
            <div class="row mt-5">
            <button class="ui secondary button" id='modal-btn'>Update your Profile</button>
            </div>
        </div>
        <div class="ten wide column">
            <table class="ui table">
                <tbody>
                    <tr>
                        <td>Username</td>
                        <td>{{profile.user}}</td>
                    </tr>
                    <tr>
                        <td>first_name</td>
                        <td>{{profile.first_name}}</td>
                    </tr>
                    <tr>
                        <td>last_name</td>
                        <td>{{profile.last_name}}</td>
                    </tr>
                    <tr>
                        <td>Bio</td>
                        <td>{{profile.bio}}</td>
                    </tr>
                    <tr>
                        <td>Created</td>
                        <td>{{profile.created}}</td>
                    </tr>
                    <tr>
                        <td>No. of Friends</td>
                        <td>{{profile.get_friends.count}}</td>
                    </tr>
                    <tr>
                        <td>All Friends</td>
                        <td>
                            <ul>
                                {% for friend in profile.get_friends %}
                                    <li>{{friend}}</li>
                                {% endfor %}
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <td>No. of Posts</td>
                        <td>{{profile.get_posts_no}}</td>
                    </tr>
                    <tr>
                        <td>No. of Likes Given</td>
                        <td>{{profile.get_all_likes_given}}</td>
                    </tr>
                    <tr>
                        <td>No. of Likes Received</td>
                        <td>{{profile.get_all_likes_received}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

</div>


 

{% endblock content %}

social_project/socialsite/profiles/templates/profiles/profile_list.html
{% extends 'base.html' %}

{% block title %}
    All Profiles
{% endblock title %}

{% block content %}
    {% if is_empty %}
        <h3>There is nothing to show.</h3>
    {% endif %}

    

    {% for obj in object_list %}
        <div class='ui segment'>
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img src="{{obj.avatar.url}}" class="ui small circular image" alt="profile-image">
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>
                        <a href="{% url 'profiles:profile-detail-view' obj.pk %}">
                        <!-- <a href="{{obj.get_absolute_url}}"> -->
                            <button class="ui primary button mb-5 w-big">See Profile</button>
                        </a>
                        {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                        <form action="{% url 'profiles:send-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name='profile_pk' value="{{obj.pk}}">
                            <button class="ui positive basic button mb-5 w-big" type="submit"><i class="plus square icon"></i>Add to friends</button>
                        </form>
                        {% endif %}
                        <br>
                        {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                            <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Waiting for Approval</button>
                                        
                        {% endif %}
                        <!-- {% if obj.user in rel_sender and request.user not in obj.friends.all %}
                            <button class="ui primary basic button mb-5 w-big"><i class="plus square icon"></i>Accept Request</button>
                                        
                        {% endif %} -->
                        {% if request.user in obj.friends.all %}
                        <form action="{% url 'profiles:remove-friend' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name='profile_pk' value="{{obj.pk}}">
                            
                            <button class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                        
                        </form>
                        {% endif %}
                        
                    </div>
                    
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

social_project/socialsite/profiles/templates/profiles/to_invite_list.html
{% extends 'base.html' %}

{% block title %}
    Invite Friends
{% endblock title %}

{% block content %}
{% if is_empty %}
    <h1>No invitation here.</h1>
{% endif %}
    <ul>
        {% for item in qs %}
            <div class="ui segment">
                <div class="ui grid">
                    <div class="row">
                        <div class="three wide column">
                            <img src={{item.avatar.url}} class="ui small circular image" alt="image">
                            
                        </div>
                        <div class="thirteen wide column">
                            <h3>{{item.user}}</h3>
                            <p>{{item.bio}}</p>
                            <a href="">
                                <button class="ui primary button w-big mb-5">See Profile</button>
                            </a>
                            <form action="" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name='profile_pk' value="{{item.pk}}">
                                <button type="submit" class="ui positive basic button w-big mb-5">
                                    <i class="check icon"></i>Accept Invite
                                </button>
                            </form>
                            <form action="" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name='profile_pk' value="{{item.pk}}">
                                <button type="submit" class="ui negative basic button w-big mb-5">
                                    <i class="close icon"></i>Reject Invite
                                </button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

    </ul>
{% endblock content %}