social_project/socialsite/posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view, like_unlike_post, PostDeleteView, PostUpdateView


app_name='posts'

urlpatterns=[
    path('', post_comment_create_and_list_view, name='main-posts-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update', PostUpdateView.as_view(), name='post-update'),
]

social_project/socialsite/profiles/urls.py
from django.urls import path
from .views import (
                    profile_view, 
                    invites_received_view,
                    invite_profiles_list_view,
                    ProfileListView,
                    # profiles_list_view,
                    send_invitation,
                    remove_from_friends,
                    accept_invitation,
                    reject_invitation,
                    ProfileDetailView,
                    )

app_name='profiles'

urlpatterns=[
    path('myprofile', profile_view, name='profile'),
    
    path('all-profiles/', ProfileListView.as_view(), name='all-profiles-view'),
    path('<int:pk>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invitation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('my-invites/accept/', accept_invitation, name='accept-invite'),
    path('my-invites/reject/', reject_invitation, name='reject-invite'),
]

social_project/socialsite/socialsite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('accounts/', include('allauth.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

social_project/socialsite/templates/main/home.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block content %}
{{hi}}
{{user}}

{% endblock content %}

{% block scripts %}
<script>
    
</script>
{% endblock scripts %}

social_project/socialsite/templates/main/navbar.html
{% url 'posts:main-posts-view' as path_to_posts %}
{% url 'home' as path_to_home %}
{% url 'profiles:profile' as path_to_my_profile %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}
{% url 'profiles:invite-profiles-view' as path_to_potential_invites %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}

<!-- path('my-invites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invitation, name='send-invite'), 
path('all-profiles/', ProfileListView.as_view(), name='all-profiles-view'),
-->



<div class="ui inverted menu nav mb-7">
    <div class="ui container">
      <a href="{{path_to_home}}" class="{% if request.path == path_to_home %} active {% endif %} item">
          <h3>socialbook</h3>
      </a>
      {% if request.user.is_authenticated %}
      <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts%} active {% endif %} item">
          Board
      </a>
      {% endif %}
  
      <div class="right menu">
          {% if request.user.is_authenticated %}
          <div class="item">
              <div class="ui floating dropdown icon button teal"> Friends
                  <i class="dropdown icon"></i>
                  <div class="menu">
                      <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %} active {% endif %} item">
                          All Profiles
                      </a>
                      <a href="{{path_to_potential_invites}}" class="{% if request.path == path_to_potential_invites %} active {% endif %} item" class="item">
                          Send Invites
                      </a>
                      <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %} active {% endif %} item">
                          Received Invites &nbsp<div class="ui label purple horizontal">{{invites_num}}</div>
                      </a>
                  </div>
               </div>
          </div>
               <div class="item">
                <form action="" method="GET">
                  <div class="ui action left icon input">
                  <input class="prompt" type="text" name='q' placeholder="name of a friend...">
                  <i class="search icon"></i>
                  <button type='submit' class="ui button">Search</button>
                  </div>
              </form>
              </div>
          
              <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %} active {% endif %} item">
                  <img src="{{picture.url}}" class="ui avatar image">&nbsp;
                   {{ request.user }}
              </a>
  
              <a href="{% url 'account_logout' %}" class="ui item">
                  Logout
              </a>
          {% else %}
          <a href="{% url 'account_login' %}" class="ui item">
                  Login
              </a>
          {% endif %}
      </div>
    </div>
  </div>